# https://docusaurus.io/docs/deployment#deploying-to-github-pages

name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
      - name: Install dependencies
        working-directory: ./website
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: ./website
        run: yarn build

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          GIT_USER: personiumio
          USE_SSH: true
        working-directory: ./website
        run: |
          git config --global user.email "personiumio@gmail.com"
          git config --global user.name "personiumio"
          yarn install --frozen-lockfile
          yarn run publish-gh-pages
